/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 */

group = "com.projectgenerator.api"
version = "1.0.0-SNAPSHOT"

plugins {
   `java-library`
   id("maven-publish")
   id("signing")
}

application {
    mainClass.set("App")
}

tasks.withType<org.gradle.jvm.tasks.Jar> {
    destinationDirectory.set(file("build/libs"))
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(platform("org.junit:junit-bom:5.10.0"))
    testImplementation("org.junit.jupiter:junit-jupiter")
}

tasks.test {
    useJUnitPlatform()
    testLogging {
        events("passed", "skipped", "failed")
    }
}

tasks.jar {
    manifest {
        attributes("ProjectGeneratorAPI" to "com.projectgenerator.api.ProjectGeneratorAPI")
    }
    from(sourceSets.main.get().output)
}

//publishing {
  //  publications {
      //  create<MavenPublication>("mavenJava")
       // from(components["java"])

      //  pom {
        //    name.set("Project Generator API")
          //  description.set("Allow users to simply create files, directorys, search for files and more.")
          //  url.set("https://github.com/HampusKalmar/Laboration-2-module")

           // developers {
            //    developer {
                    
            //    }
          //  }
      //  }
   // }
// }

