/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 */

plugins {
    java
    application
}

application {
    mainClass.set("ProjectGeneratorImpl")
}

tasks.withType<org.gradle.jvm.tasks.Jar> {
    destinationDirectory.set(file("build/libs"))
}

